# Generated by Django 5.1.6 on 2025-02-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0002_remove_coupon_discount_percentage_coupon_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='number',
            new_name='count',
        ),
    ]
