# Generated by Django 5.1.6 on 2025-02-27 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0003_rename_number_seat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lounge_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zenapp.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='seat_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
