# Generated by Django 5.1.6 on 2025-02-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0005_remove_event_duration_event_from_timee_event_to_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
    ]
