# Generated by Django 5.1.6 on 2025-02-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0006_remove_event_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='from_timee',
            new_name='from_time',
        ),
    ]
