# Generated by Django 5.1.6 on 2025-02-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0007_rename_from_timee_event_from_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='from_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='to_time',
            new_name='start_time',
        ),
    ]
