# Generated by Django 5.1.6 on 2025-03-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_remove_paymentgateway_public_key_and_more'),
        ('zenapp', '0013_payment_payment_gateway_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authapp.paymentgateway'),
            preserve_default=False,
        ),
    ]
