# Generated by Django 5.1.6 on 2025-03-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zenapp", "0016_alter_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="registration_id",
            field=models.CharField(default="", max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
