# Generated by Django 5.1.6 on 2025-03-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zenapp", "0017_eventregistration_registration_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="payment_status",
            field=models.CharField(
                blank=True, default="Pending", max_length=20, null=True
            ),
        ),
    ]
