# Generated by Django 5.1.6 on 2025-03-07 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zenapp", "0018_alter_eventregistration_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
