# Generated by Django 5.1.6 on 2025-03-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zenapp", "0019_event_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="registration_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
