# Generated by Django 5.1.6 on 2025-03-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0025_alter_eventregistration_registration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_id',
            field=models.CharField(blank=True, default='REGIS321240', max_length=100, null=True),
        ),
    ]
