# Generated by Django 5.1.6 on 2025-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0026_alter_eventregistration_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_id',
            field=models.CharField(blank=True, default='REGIS264621', max_length=100, null=True),
        ),
    ]
