# Generated by Django 5.1.6 on 2025-03-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0027_alter_eventregistration_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_id',
            field=models.CharField(blank=True, default='REGIS147763', max_length=100, null=True),
        ),
    ]
