# Generated by Django 5.1.6 on 2025-05-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenapp', '0028_alter_event_end_date_alter_event_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_id',
            field=models.CharField(default=1, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
