
from .university_viewset import UniversityViewSet
from .intrested_topic_viewset import IntrestedTopicViewSet
from .user_viewset import CustomUserViewSet
from .payment_gateway_viewset import PaymentGatewayViewSet
from .group_viewset import GroupViewSet