# Generated by Django 5.1.6 on 2025-02-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='intrested_topics',
            field=models.ManyToManyField(blank=True, null=True, to='authapp.intrestedtopic'),
        ),
    ]
