# Generated by Django 5.1.6 on 2025-03-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_paymentgateway_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='credentials',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='name',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('ccavenue', 'CCAvenue'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=100, unique=True),
        ),
    ]
