# Generated by Django 5.1.6 on 2025-03-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_country_customuser_is_open_to_be_mentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='intrested_topics',
        ),
        migrations.AddField(
            model_name='customuser',
            name='intrested_topics',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
