# Generated by Django 5.1.6 on 2025-03-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_remove_customuser_intrested_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='year_of_graduation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
