# Generated by Django 5.1.6 on 2025-05-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_customuser_year_of_graduation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='intrested_topics',
        ),
        migrations.AddField(
            model_name='customuser',
            name='interested_topics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
