# Generated by Django 5.1.6 on 2025-05-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_remove_customuser_intrested_topics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='interested_topics',
            new_name='intrested_topics',
        ),
    ]
