# Generated by Django 5.1.6 on 2025-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='intrested_topics',
        ),
        migrations.AddField(
            model_name='customuser',
            name='intrested_topics',
            field=models.ManyToManyField(blank=True, to='authapp.intrestedtopic'),
        ),
    ]
